CREATE TABLE [dbo].[Orders] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [OrderDate]             DATETIME        DEFAULT (getdate()) NOT NULL,
    [Subtotal]              DECIMAL (18, 2) NOT NULL,
    [ShippingFee]           DECIMAL (18, 2) NOT NULL,
    [TaxAmount]             DECIMAL (18, 2) NOT NULL,
    [DiscountAmount]        DECIMAL (18, 2) NOT NULL,
    [TotalAmount]           DECIMAL (18, 2) NOT NULL,
    [Status]                NVARCHAR (50)   NOT NULL,
    [CustomerName]          NVARCHAR (100)  NOT NULL,
    [CustomerEmail]         NVARCHAR (100)  NOT NULL,
    [ShippingAddress]       NVARCHAR (500)  NOT NULL,
    [CourierName]           NVARCHAR (100)  NULL,
    [TrackingNumber]        NVARCHAR (100)  NULL,
    [TrackingUrl]           NVARCHAR (500)  NULL,
    [RazorpayOrderId]       NVARCHAR (100)  NULL,
    [PaymentStatus]         NVARCHAR (50)   DEFAULT ('Pending') NULL,
    [RazorpayPaymentId]     NVARCHAR (100)  NULL,
    [ShippingAddressLine1]  NVARCHAR (500)  NULL,
    [ShippingAddressLine2]  NVARCHAR (500)  NULL,
    [ShippingCity]          NVARCHAR (100)  NULL,
    [ShippingState]         NVARCHAR (100)  NULL,
    [ShippingCountry]       NVARCHAR (100)  NULL,
    [ShippingPostalCode]    NVARCHAR (50)   NULL,
    [ShippingContactNumber] NVARCHAR (50)   NULL,
    [ShippingLandmark]      NVARCHAR (255)  NULL,
    [RazorpaySignature]     NVARCHAR (200)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

