name: Sync to Release Repo

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Destination Repository
        env:
          DESTINATION_REPO: https://${{ secrets.SYNC_WOWMEN_RELEASE }}@github.com/wowmenfashions-dot/WOWMENFASHIONS.git
        run: |
          git remote add destination $DESTINATION_REPO
          # We push the local develop branch to the remote release branch
          git push destination HEAD:refs/heads/release --force
